---
apiVersion: v1
description: Helm chart for generic app on Kubernetes
maintainers:
  - name: QJOLY
    email: github@une-pause-cafe.fr
    url: https://une-tasse-de.cafe
name: common
version: v0.4.2
appVersion: "0"
kubeVersion: ">= 1.18"
home: https://github.com/RubxKube/common-charts
keywords:
  - generic
  - monolithic
  - ingress
sources:
  - https://github.com/RubxKube/common-charts
